version: "3.3"
services:

  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mystart
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432