micronaut:
  application:
    name: mystart
  router:
    static-resources:
      default:
        paths: "classpath:public"
        mapping: "/**/*"
        enabled: true    
  security:
    enabled: true
    intercept-url-map:
      - pattern : /api/registration/**
        access:
          - isAnonymous()
      - pattern : /api/**
        access:
          - isAuthenticated()
      - pattern : /**
        access:
          - isAnonymous()

